version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: estanoesunaclave
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: estanoesunaclave
    ports:
      - "81:8080"
    depends_on:
      - db

  account:
      build:
        context: ./account
        dockerfile: Dockerfile
      environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
        SPRING_DATASOURCE_USERNAME: postgres
        SPRING_DATASOURCE_PASSWORD: estanoesunaclave
      ports:
        - "82:8080"
      depends_on:
        - db
        - client

